# Run `cp gcp_compute_example.yaml gcp_compute.yaml` before executing the ansible playbook!
plugin: google.cloud.gcp_compute
zones:
  - YOUR_GCP_ZONE
projects:
  - YOUR_GCP_PROJECT_ID
filters:
  - status = RUNNING
  - scheduling.automaticRestart = true AND status = RUNNING
service_account_file: YOUR_GCP_SERVICE_ACCOUNT_FILE_PATH
auth_kind: serviceaccount
scopes:
  - 'https://www.googleapis.com/auth/cloud-platform'
  - 'https://www.googleapis.com/auth/compute.readonly'
keyed_groups:
  - prefix: gcp
    key: labels
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP